- name: reconfig
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - src: kyuubi-defaults.conf
      dest: '{{ kyuubi_home }}/conf/kyuubi-defaults.conf'
    - src: kyuubi-env.sh
      dest: '{{ kyuubi_home }}/conf/kyuubi-env.sh'
