- name: reconfig
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ spark_home }}/conf/{{ item.file }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: "spark-defaults.conf", mode: "644" }
