- file:
    path: "{{ home }}/.pip"
    state: directory
    mode: 0755

- copy:
    src: "{{ item }}"
    dest: "{{ home }}/.pip/{{ item }}"
    mode: 0644
    force: yes
  with_items:
    - "pip.conf"
