- file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: 0755

- copy:
    src: "ssh/{{ item.file }}"
    dest: "{{ home }}/.ssh/{{ item.file }}"
    mode: "{{ item.mode }}"
    force: yes
  with_items:
    # - { file: "id_rsa", mode: "600" }
    - { file: "id_rsa.pub", mode: "644" }

- template:
    src: "ssh/{{ item.file }}.j2"
    dest: "{{ home }}/.ssh/{{ item.file }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: "config", mode: "600" }
