# usage:
#   ansible-playbook playbooks/cfg.yaml -t bin
#   ansible-playbook playbooks/cfg.yaml -t npm
#   ansible-playbook playbooks/cfg.yaml -t pip
#   ansible-playbook playbooks/cfg.yaml -t ssh
##
---
- hosts: local
  gather_facts: True
  tasks:
    - include_role:
        name: "../roles/cfg"
        tasks_from: bin
        apply:
          tags: bin
      tags: bin

    - include_role:
        name: "../roles/cfg"
        tasks_from: npm
        apply:
          tags: npm
      tags: npm

    - include_role:
        name: "../roles/cfg"
        tasks_from: pip
        apply:
          tags: pip
      tags: pip

    - include_role:
        name: "../roles/cfg"
        tasks_from: ssh
        apply:
          tags: ssh
      tags: ssh
