# usage:
#   ansible-playbook playbooks/debug.yaml
##
---
- hosts: local
  gather_facts: True
  tasks:
    - debug:
        msg: "{{ ansible_user_id }}"
    - debug:
        msg: "{{ ansible_user_dir }}"
    - debug:
        msg: "{{ ansible_env.SHELL }}"
    - debug:
        msg: "{{ ansible_facts.architecture }}"
    - debug:
        msg: "{{ app_home }}"
